# Generated by Django 4.2.13 on 2024-08-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEVERAGE_ONE', models.BooleanField(default=False)),
                ('LEVERAGE_TWO', models.BooleanField(default=False)),
                ('LEVERAGE_THREE', models.BooleanField(default=False)),
                ('LEVERAGE_FOUR', models.BooleanField(default=False)),
                ('demand', models.FloatField(default=0)),
                ('supply', models.FloatField(default=0)),
                ('B_A_VALUE', models.FloatField(default=10)),
                ('TRANSACTIONS', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('score', models.FloatField()),
                ('value', models.FloatField()),
                ('limit', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('A', models.FloatField(default=300)),
                ('B', models.FloatField(default=20)),
                ('score', models.FloatField()),
                ('stat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('game', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='main.team')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenders', to='main.team')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='main.team')),
            ],
        ),
    ]
