# Generated by Django 4.2.13 on 2024-07-25 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('A', models.FloatField()),
                ('B', models.FloatField()),
                ('score', models.IntegerField()),
                ('stat', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='main.team')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenders', to='main.team')),
                ('winner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='main.team')),
            ],
        ),
    ]
