# Generated by Django 4.2.13 on 2024-08-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='attacker_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='defender_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
