# Generated by Django 4.2.13 on 2024-07-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='main.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='stat',
            field=models.IntegerField(default=0),
        ),
    ]
