# Generated by Django 4.2.13 on 2024-07-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_game_id_alter_game_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameTeam',
        ),
    ]
