# Generated by Django 4.2.13 on 2024-07-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gameteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameteam',
            name='team',
        ),
    ]
