# Generated by Django 4.2.13 on 2024-07-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_gameteam_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameTeam',
        ),
    ]
