# Generated by Django 4.2.13 on 2024-07-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_game_id_alter_game_name_gameteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameteam',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameteam',
            name='team',
        ),
    ]
