# Generated by Django 4.2.13 on 2024-07-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_gameteam_game_remove_gameteam_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.game'),
        ),
        migrations.AddField(
            model_name='gameteam',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
