# Generated by Django 4.2.13 on 2024-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_gameteam_game_gameteam_team_alter_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionstat',
            name='solved',
        ),
        migrations.AddField(
            model_name='questionstat',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
