# Generated by Django 4.2.13 on 2024-07-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_questionstat_solved_questionstat_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='limit',
            field=models.IntegerField(default=2),
        ),
    ]
