# Generated by Django 4.2.13 on 2024-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_game_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEVERAGE_ONE', models.BooleanField(default=False)),
                ('LEVERAGE_TWO', models.BooleanField(default=False)),
                ('LEVERAGE_THREE', models.BooleanField(default=False)),
                ('LEVERAGE_FOUR', models.BooleanField(default=False)),
                ('demand', models.IntegerField(default=0)),
                ('supply', models.IntegerField(default=0)),
                ('B_A_VALUE', models.FloatField(default=10)),
                ('TRANSACTIONS', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='A',
            field=models.FloatField(default=300),
        ),
        migrations.AlterField(
            model_name='team',
            name='B',
            field=models.FloatField(default=20),
        ),
    ]
