# Generated by Django 4.2.13 on 2024-08-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_allinfo_demand_alter_allinfo_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.FloatField(),
        ),
    ]
